### ISSUE TITLE
Additional row of fees is added in the parent order. 

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/checkout-fees-for-woocommerce#11]
When a subscription order is placed, then in Edit order page, a new additional row of fee with '0' price is added.

Attaching a screenshot: https://prnt.sc/ndnrs1

Screenshot: https://prnt.sc/ndo90x

**Comment by mokshasharmila13** [comment]
This issue is not replicated, installed a WooCommerce subscription and placed new order but in the Edit order page, a new additional row of fees with a '0' price is not added.

**Video**:- https://www.awesomescreenshot.com/video/19248246?key=59b1c1c16bd9ed1f9472bbd2dd8303bd
