### ISSUE TITLE
When our plugin is activated, payment methods collapses a moment after the page loads on "Chance Payment" button of Subscription order.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#118]
**Describe the bug**

I am using WordPress (6.0.2), WooCommerce (6.9.3), WooCommerce Subscriptions (3.1.2) and Payment Gateway Based Fees and Discounts for WooCommerce (2.7.0) plugins.

If on the “My Subscription” page I click the “Add payment” or “Change payment” button. My list of payment methods collapses a moment after the page loads.

The problem is only if I want to change the payment method. If I do not change the payment method, but add it, then everything works. Shown in screenshots:

Screenshot 1 – while the page is loading
Screenshot 2 – after full page load
**To Reproduce**
I can replicate this on my staging site.
1. Create subscription orders
2. Go to My Account > Subscription page and you'll see change Payment button for the order. 

The subscription must be 'active' for the buttons to appear and the order status must be 'completed' or 'processing' for the bug to appear.

Please make sure you have extra Stripe or paypal payment gateway activated for the site to show "Change Payment" button. 

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/46064

**Comment by Chetna1510** [comment]
The client has shared the suggestion:

1. https://prnt.sc/NwqozQn3fF0M
2. woocommerce-subscriptions/includes/class-wc-subscriptions-change-payment-gateway.php ( https://prnt.sc/AcpF8OTf7J7r )
"For the recurring payment method to be changeable, the subscription must be active, have future (automatic) payments and use a payment gateway which allows the subscription to be cancelled".

**Comment by mital-tyche** [comment]
This one is not replicated in our site. It is replicated on client site.
