### ISSUE TITLE
Payment fee is not removing when the shipping method is changed.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/checkout-fees-for-woocommerce#13]
Describe the bug
Payment fee set for COD method is not removing from Your order table when the shipping method is changed.

To Reproduce

1) Cod payment method will be available only for Free shipping, Local Pickup shipping methods.
2) Visit the checkout page and select free shipping method.
3) COD fees will be added to the Your order table.
4) Now change the shipping method say to Flat rate for which COD is not available.
5) the issue is replicated where the COD fees are not removed from the table.

Screenshots or Video
https://prnt.sc/nlgv97 , https://prnt.sc/nlgvkz
video: https://drive.google.com/file/d/1iXnM2sCMz9VFEPUIsQ6FlYCuiAVyRwMb/view?usp=sharing

**Comment by kenil802** [comment]
One more client is facing the same issue.

Link: https://wordpress.org/support/topic/payment-fee-not-removed-after-selecting-different-shipping-method/

**Comment by Shasvat7** [comment]
This issue is not getting replicated with the latest git copy.
Here's the video for the same: https://www.awesomescreenshot.com/video/5329223?key=77dfba19504fe302add1b006d520246e
Screenshot: https://prnt.sc/1t819r6 https://prnt.sc/1t81s9o
Hence, closing this issue
