### ISSUE TITLE
When we try to repay the order, the button to place an order disappears for Paypal and Credit card. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#131]
**Describe the bug**
When the plugin is activated, the PayPal button disappears on the Pay Order page.

**To Reproduce**
1.  Install "WooCommerce PayPal Payments" plugin
2. Setup Paypal and Credit Cart
3. You also need to tick this box.
![MedQT3G-YglvDbE8iT1kRkOCmqghvDdmSQ](https://user-images.githubusercontent.com/15136179/230918977-c41813f2-d8a9-439a-96a2-d412c6f3dff6.png)
4. Then a new PayPal tab will appear.
![38SMq327Uc88Fn1bVDgHT3-DI-65J1xfAg (1)](https://user-images.githubusercontent.com/15136179/230922625-2a4b734e-4c2f-4aa3-8a5c-e38834cb3458.png)

5. Now, try to access the page when you try to repay the order and select "Paypal" or "Credit Card" option. It will disappear when our plugin is activated. 

I'm also able to replicate on my staging site. 

**Expected behavior**
The button should be there even when our plugin is activated. 

**Screenshots**

https://user-images.githubusercontent.com/15136179/230921451-e6532e06-75a5-4389-8f04-0533a29859b6.mp4

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/52906

**Comment by mital-tyche** [comment]
With the latest version of our plugin. this issue is not longer replicated.
@Chetna1510 also check this one but not replicated on her site also.

**Comment by Chetna1510** [comment]
I'm also unable to replicate with the latest version

**Comment by mokshasharmila13** [comment]
This issue is not able to be replicated. The PayPal and credit card buttons appear and work properly.
