### ISSUE TITLE
Incompatibility with ECPay plugin

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#138]
**Describe the bug**
Incompatibility with ECPay plugin

**To Reproduce**
1. Install this plugin - https://tw.wordpress.org/plugins/ecpay-ecommerce-for-woocommerce/
2. Our plugin's settings are not being appeared - 
![image](https://user-images.githubusercontent.com/15136179/236268629-c46b5f8f-85a1-4497-9f7d-1da1c3b9d6e9.png)

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/53722

**Comment by mital-tyche** [comment]
After Activate Ecapy, on PGBF setting page all Ecpay related setting label is not displaying.
https://prnt.sc/4JK_LiPIyl9r
Hence, I open the issue.
