### ISSUE TITLE
Add tracking data in plugin: Settings, admin choice and data tracking

### ISSUE THREAD

**Issue by pinalj** [TycheSoftwares/checkout-fees-for-woocommerce#153]
Describe the bug
Add the data tracking code in the plugin to ensure all the relevant details (global settings, product settings etc.) are sent back to the tracking server.

Additional context
https://docs.google.com/document/d/1T-4QcwvO1K-dZLFQwOxC_xvPjX4QFFXuSqt1bNn7lU4/edit

The tracking code needs to be implemented at v2

Tyche Javascript Constructor: https://github.com/TycheSoftwares/tyche-js-constructor
Plugin Tracking: https://github.com/TycheSoftwares/tyche-plugin-tracking
Plugin Deactivation: https://github.com/TycheSoftwares/tyche-plugin-deactivation

**Comment by apeksha10** [comment]
Re-opening this issue,

I'm currently testing the plugin deactivation feature, I found difficulties in searching the tracking ID for the website, and while I successfully identified the website tracking ID during the implementation of the data tracking component

**Comment by apeksha10** [comment]
I found the website id now, may be server issue at that time 

closing this issue
