### ISSUE TITLE
 Currently, only the Fixed amount can be set for the 'Global Extra Fee' in our plugin and not the percentage fee.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/checkout-fees-for-woocommerce#16]
Currently, only the Fixed amount can be set for the 'Global Extra Fee' in our plugin and not the percentage fee.

We can add the percent type as well like we have for individual payment gateway settings.

Forum: https://wordpress.org/support/topic/percentage-global-extra-fee/

**Comment by mital-tyche** [comment]
This issue is moved to the next milestone 2.11.0.
hence I open it.
