### ISSUE TITLE
Getting "Internal Server" error on checkout page with php 8.2.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#162]
**Describe the bug**
Getting "Internal Server" error on the checkout page.

**To Reproduce**
1. Updated the plugin to v2.10.1.
2. Here is the setup - 
![image](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/assets/15136179/f1f81759-5cde-426e-a34c-3ce2094b6495)
![image](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/assets/15136179/8c90af80-48c5-4134-aade-caca44a7f2de)

When I try to place an order, I got an error - 
![image](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/assets/15136179/28a39ab4-b394-4c44-8d7e-4f95d5396e2b)

Received this error in debug log file:
2023-06-26T16:16:30+00:00 CRITICAL Uncaught TypeError: Unsupported operand types: float + string in C:\xampp\htdocs\wordpress.local\wp-content\plugins\checkout-fees-for-woocommerce\includes\class-alg-wc-order-fees.php:782
Stack trace:
#0 C:\xampp\htdocs\wordpress.local\wp-content\plugins\checkout-fees-for-woocommerce\includes\class-alg-wc-order-fees.php(420): Alg_WC_Order_Fees->calculate_the_fee(Array, 1.389, 13.89, 'fee_2', Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 C:\xampp\htdocs\wordpress.local\wp-content\plugins\checkout-fees-for-woocommerce\includes\class-alg-wc-order-fees.php(289): Alg_WC_Order_Fees->get_the_fee(Object(Automattic\WooCommerce\Admin\Overrides\Order), Array, 'fee_both')
#2 C:\xampp\htdocs\wordpress.local\wp-content\plugins\checkout-fees-for-woocommerce\includes\class-alg-wc-order-fees.php(217): Alg_WC_Order_Fees->maybe_add_order_fee(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#3 C:\xampp\htdocs\wordpress.local\wp-content\plugins\checkout-fees-for-woocommerce\includes\class-alg-wc-order-fees.php(110): Alg_WC_Order_Fees->add_gateways_fees(Object(Automattic\WooCommerce\Admin\Overrides\Order), 'bacs')
#4 C:\xampp\htdocs\wordpress.local\wp-includes\class-wp-hook.php(310): Alg_WC_Order_Fees->alg_wc_cf_update_order_fees(33, Object(WP_Post))
#5 C:\xampp\htdocs\wordpress.local\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#6 C:\xampp\htdocs\wordpress.local\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#7 C:\xampp\htdocs\wordpress.local\wp-includes\post.php(4715): do_action('save_post', 33, Object(WP_Post), true)
#8 C:\xampp\htdocs\wordpress.local\wp-includes\post.php(4817): wp_insert_post(Array, false, true)
#9 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\data-stores\abstract-wc-order-data-store-cpt.php(185): wp_update_post(Array)
#10 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\data-stores\class-wc-order-data-store-cpt.php(188): Abstract_WC_Order_Data_Store_CPT->update(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#11 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\class-wc-data-store.php(196): WC_Order_Data_Store_CPT->update(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#12 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-order.php(212): WC_Data_Store->update(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#13 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\class-wc-order.php(244): WC_Abstract_Order->save()
#14 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\class-wc-order.php(357): WC_Order->save()
#15 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\gateways\bacs\class-wc-gateway-bacs.php(371): WC_Order->update_status('on-hold', 'Awaiting BACS p...')
#16 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\class-wc-checkout.php(1050): WC_Gateway_BACS->process_payment(33)
#17 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\class-wc-checkout.php(1279): WC_Checkout->process_order_payment(33, 'bacs')
#18 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\class-wc-ajax.php(485): WC_Checkout->process_checkout()
#19 C:\xampp\htdocs\wordpress.local\wp-includes\class-wp-hook.php(308): WC_AJAX::checkout('')
#20 C:\xampp\htdocs\wordpress.local\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#21 C:\xampp\htdocs\wordpress.local\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#22 C:\xampp\htdocs\wordpress.local\wp-content\plugins\woocommerce\includes\class-wc-ajax.php(96): do_action('wc_ajax_checkou...')
#23 C:\xampp\htdocs\wordpress.local\wp-includes\class-wp-hook.php(308): WC_AJAX::do_wc_ajax('')
#24 C:\xampp\htdocs\wordpress.local\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(false, Array)
#25 C:\xampp\htdocs\wordpress.local\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#26 C:\xampp\htdocs\wordpress.local\wp-includes\template-loader.php(13): do_action('template_redire...')
#27 C:\xampp\htdocs\wordpress.local\wp-blog-header.php(19): require_once('C:\\xampp\\htdocs...')
#28 C:\xampp\htdocs\wordpress.local\index.php(17): require('C:\\xampp\\htdocs...')
#29 {main}
  thrown in C:\xampp\htdocs\wordpress.local\wp-content\plugins\checkout-fees-for-woocommerce\includes\class-alg-wc-order-fees.php on line 782
**Additional context**

**Comment by Chetna1510** [comment]
One client has reported this - https://tychesoftwares.freshdesk.com/a/tickets/55163

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/55103

**Comment by mital-tyche** [comment]
You need to check with all fees like percentage, fixed...
Also need to check with fees is deducted as ( Point value = 5.74, INT value = 5 ).
Check with discount also. where we add minus fees ( -5 ).

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/55266
