### ISSUE TITLE
Fees is getting duplicated after an order has been placed.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#164]
**Describe the bug**
When a customer fills their cart and proceeds to checkout everything is calculated just fine. But after placing the order the discount of 1% for bank transfer is saved twice in the database (actually, once for the products without shipping as defined in our settings, and once for the full price incl. shipping).
The customer will then receive their confirmation mail showing the discount twice (with different values) but the value of their whole order is still correct as it shows the price that was shown during the checkout, subtracting the discount only once.

**To Reproduce**
I'm also able to replicate the issue on my staging site with the below setup: 

1. General Settings:
![image](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/assets/15136179/89714896-0cb1-491d-9249-14a556062228)

2. 
![image](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/assets/15136179/b88ea749-4451-4f51-8067-7f34ab6fb274)

![image](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/assets/15136179/3f22d9ec-4498-4244-9834-581f65a06d0b)

Result: 
![image](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/assets/15136179/02343a8f-4dcf-4402-ad76-969dc55b2c55)

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/55051

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/55264

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/55065

**Comment by Chetna1510** [comment]
https://wordpress.org/support/topic/its-showing-two-time-fees-in-order-meta/

**Comment by apeksha10** [comment]
The Original issue is fixed now but @mital suggest I to test the https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/issues/31 issue  

#31 is replicated with the latest git copy. Hence I have put fixed label on the above issue and re-opened #31
