### ISSUE TITLE
Compatibility with Mercado Pago Payment Gateway Plugin

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#17]
Payment Gateway Based Fees and Discounts for WooCommerce plugin is not compatible with Mercado Pago Payment Gateway.

Link of the plugin: https://wordpress.org/plugins/woocommerce-mercadopago/

The fee is not passing to the gateway. It is added only on the checkout page.
Client issue link: https://wordpress.org/support/topic/compatibility-with-mercadopago-gateway/

Screenshot for the reference:
https://prnt.sc/omg434
https://prnt.sc/omg4l7

**Comment by entorno-digital** [comment]
same
