### ISSUE TITLE
Getting Fatal Error when we refund the order. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#171]
**Describe the bug**
As the title, the plugin will error when i refund the order in the current version. There is the error massage below.

2023-07-08T08:57:51+00:00 CRITICAL Uncaught Error: Call to undefined method Automattic\WooCommerce\Admin\Overrides\OrderRefund::get_payment_method() in /home/team-sandbox/public_html/chetna/wp-content/plugins/checkout-fees-for-woocommerce/includes/class-alg-wc-order-fees.php:114
Stack trace:
#0 /home/team-sandbox/public_html/chetna/wp-includes/class-wp-hook.php(310): Alg_WC_Order_Fees->alg_wc_cf_update_order_fees()
#1 /home/team-sandbox/public_html/chetna/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /home/team-sandbox/public_html/chetna/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /home/team-sandbox/public_html/chetna/wp-includes/post.php(4715): do_action()
#4 /home/team-sandbox/public_html/chetna/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php(97): wp_insert_post()
#5 /home/team-sandbox/public_html/chetna/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(186): Abstract_WC_Order_Data_Store_CPT->create()
#6 /home/team-sandbox/public_html/chetna/wp-content/plugins/ in /home/team-sandbox/public_html/chetna/wp-content/plugins/checkout-fees-for-woocommerce/includes/class-alg-wc-order-fees.php on line 114

**To Reproduce**
1. Update to v2.10.2.
2. Mark the order as "Refund"
3. You will see the Fatal error.

I'm able to replicate on my site. 

**Additional context**
https://wordpress.org/support/topic/error-when-i-refund/

**Comment by Chetna1510** [comment]
https://wordpress.org/support/topic/error-with-refund-on-version-2-10-2/

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/55540

**Comment by mital-tyche** [comment]
This issue fixed is added in issue #31. Hence I close it.

**Comment by upenkapse** [comment]
One more customer reported the issue: https://tychesoftwares.freshdesk.com/a/tickets/55613
