### ISSUE TITLE
Global-level payment gateway fees do not get added with PHP 8.2.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/checkout-fees-for-woocommerce#176]
**Describe the bug**
Global-level payment gateway fees do not get added with PHP 8.2.

**To Reproduce**
1. Global-level payment gateway fees setup. https://app.screencast.com/g8Bz570sDtovU, https://app.screencast.com/1wK8c7Kg0On1u
2. Product-level payment gateway fees setup. https://app.screencast.com/DdALzwBgL7ETP
3. Add product to the cart page, I noticed that global-level fees do not get added in your table where as global-level additional fees are added fine. https://app.screencast.com/HK7KROenx3EHW

This issue is replicated with PHP 8.2 only. 

**Expected behavior**
Global-level payment gateway fees should get added with PHP 8.2.

**Comment by mital-tyche** [comment]
Hello @apeksha10 
https://app.screencast.com/DdALzwBgL7ETP
In this screenshot you selected override global fees checkbox...
That's why is not getting applied Can you please check it
