### ISSUE TITLE
The fees added while creating the manual order, it is gets to zero when our plugin is activated. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#195]
**Describe the bug**
The fees added while creating the manual order, it is gets to zero when our plugin is activated. 

**To Reproduce**
1. Go to Order > Add Order page
2. click on "Add item > Add fee" button and add the fees and create pending order.
3. click on the link to more for paying the order and the total has become 0 when our plugin is activated.

Video: https://drive.google.com/file/d/1RhPqkTJoBiqASx8tHB4tDv4t4JgFdLgu

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/57297

**Comment by Chetna1510** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github #195](https://trello.com/c/TMjkw8CB/25-github-195)

**Comment by mital-tyche** [comment]
This issue is not replicated with latest git copy.
The solution for issue #182 is solve this issue as well.
