### ISSUE TITLE
The Tax being applied to the payment gateway fees after updating the order status to 'Completed,' even when the Tax setting is not enabled in the necessary payment gateway.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/checkout-fees-for-woocommerce#198]
**Describe the bug**
The Tax being applied to the payment gateway fees after updating the order status to 'Completed,' even when the Tax setting is not enabled in the necessary payment gateway.

**To Reproduce**
1. Enable 'Payment Gateway Based Fees and Discounts' and enable '"Cash on delivery" fees and discounts' with 10% fee value and without taxes: https://prnt.sc/jdfg5WV4Ijxq , https://prnt.sc/LFFnWWr-pe9z
2. Enable Tax with 'Yes, I will enter prices inclusive of tax' set to 'Prices entered with tax' option and inclusive to all the other settings: https://prnt.sc/nrnQWWAtJDHL
3. Set 10% value to the Standard Tax rate
4. Now, when the product is ordered, the tax is not calculated on the payment fees: https://prnt.sc/MRFPNMCnFZ-9
5. As the order status is updated to Completed, the tax of 10% is added to the payment fees: https://prnt.sc/J3eSnV5hQ1Hl

**Expected behavior**
Tax should not be applied even after the order is updated to Completed status as the Tax setting is disabled in the payment gateway settings.

**Additional context**
Ticket: https://tychesoftwares.freshdesk.com/a/tickets/58607

**Comment by komal-maru** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #198](https://trello.com/c/sLMjDkiC/26-issue-198)

**Comment by mital-tyche** [comment]
This issue was not replicated on git copy.
The one fix moved by @gaminikhil for the issue #185. Because of this fix the issue was no longer replicated on git copy.
File name - class-alg-wc-order-fees.php. Function - alg_wc_cf_update_order_fees.

Hello @komal-maru 
if you want to send fix to the client. Please let me know. or you can directly download the file from git and send it to client.
