### ISSUE TITLE
Payment gateway fees are not visible on the Checkout block page.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/checkout-fees-for-woocommerce#199]
**Describe the bug**
Payment gateway fees are not visible on the Checkout block page. 

**To Reproduce**
1. Settings. https://app.screencast.com/iJZspuZqcwmIl
2. Add the product
3. Go to the Checkout block page the gateway fees do not appear on the checkout block page.

Checkout block page. : https://app.screencast.com/yMJy1glwYnxAN

**Expected behavior**
Payment gateway fees should be visible on the checkout block page.

**Comment by Chetna1510** [comment]
One client has raised for compatibility - https://wordpress.org/support/topic/compatible-with-woocommerce-8-4/

**Comment by komal-maru** [comment]
One more client has reported this issue: https://support.tychesoftwares.com/conversation/178?folder_id=13

**Comment by Chetna1510** [comment]
https://support.tychesoftwares.com/conversation/539?folder_id=9

**Comment by gaminikhil** [comment]
The payment gateway fee is showing, but when I change the payment option, it does not change the fee according to the selected payment gateway.
[https://prnt.sc/O1As606wpnSY](url)
