### ISSUE TITLE
Percentage on Frontend are not Calculated the right way.

### ISSUE THREAD

**Issue by Wicht1** [TycheSoftwares/checkout-fees-for-woocommerce#216]
**Describe the bug**
When I use the INFO Tab, to Show the Discount for a specific Product, it shows 0%. If I put the Product in the Cart, the INFO Tab works as aspected.

**To Reproduce**
1. Go to https://dezentralshop.ch/produkt/der-bitcoin-standard/
2. Click on "Put it in Cart"
3. You see the Discount

**Expected behavior**
Show the Discount on the first visit of the page

**Screenshots**

![Bildschirmfoto 2024-01-26 um 12 39 18](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/assets/30580105/9fbd6095-846b-4695-9fa1-6c7a53436041)
![Bildschirmfoto 2024-01-26 um 12 39 31](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/assets/30580105/c6707e22-3169-498a-9f41-7f31f9ce692e)

**Desktop (please complete the following information):**
Tested on Chrome, Firefox, Safari - everywhere the same

**Additional context**
Set payment gateways fees and discounts in WooCommerce.
Version 2.10.0 | Von [Tyche Softwares](https://www.tychesoftwares.com/)

**Comment by mokshasharmila13** [comment]
This issue is not replicated, and the fees are displayed and calculated correctly on the frontend in both fixed and percent options.
