### ISSUE TITLE
Fee is not getting calculated when order is created in the backend-manually

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#25]
When an order is created in the backend-manually, the fee is not getting calculated.

Suppose the PayPal fee is kept 5%.

1.  Create the order by clicking on Add Order button and keep the payment status to "Pending 
     Payment". Screenshot: https://prnt.sc/p52oog https://prnt.sc/p52r3i
2.  Now, on the My Account>> Orders page, you will see a Pay button for this Pending Payment 
     order. Screenshot: https://prnt.sc/p52pfs
3.  When you click on this Pay button it will be redirected to an Order Pay page and there the 
    payment gateway fee is not calculated. Screenshot: https://prnt.sc/p52rp3
 
The same issue is there in the Pro version also.

**Comment by kenil802** [comment]
One client has faced this issue.

Ticket link: https://wordpress.org/support/topic/fees-not-showing-link-url-from-email/

**Comment by Shasvat7** [comment]
Same as #14 
This issue is been fixed in v2.6.3. PR for this issue: #65 
Hence, closing this issue.
