### ISSUE TITLE
While selecting PayPal option as payment gateway the plugin always use the standard tax rate

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#27]
When enabling taxes, you can select which tax rate to be applied, the problem is, no matter if you select the reduced rate or zero rates that the plugin always uses the standard rate tax while selecting the PayPal payment gateway.

Ticket Link: https://tychesoftwares.freshdesk.com/a/tickets/10486
Screenshots: https://prnt.sc/pkjrzs https://prnt.sc/pkjw5z  https://prnt.sc/pkjwgx

**Comment by Shasvat7** [comment]
With the latest git copy, I am unable to replicate this issue and the tax on fees is getting added correctly.
Hence, closing this issue.
Screenshots:
https://prnt.sc/1t72tze
https://prnt.sc/1t734al
https://prnt.sc/1t72x1j
https://prnt.sc/1t72hd9
https://prnt.sc/1t732j9
