### ISSUE TITLE
Discount amount is added even if we select another payment gateway which does not have the discount amount set.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#29]
Steps to replicate the issue:

1) The client has 3 payment gateways and he is offering the 10% discount only on 2nd and 3rd payment gateways.
2) Now, if one customer selects the second payment gateway and places an order but the payment is not done so the order will be placed with Pending Payment status.
3) Now this customer goes to his My Account page, and under Orders, he will see this Pending order with a Pay Now link - he clicks on the Pay Now link and on the next page he completes the order with the first payment gateway but he will still get the 10% discount.

Screenshot: https://prnt.sc/rhm7yy

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/14737

**Comment by mokshasharmila13** [comment]
This issue is not replicated, After adding a 3rd party payment (Alipay/credit card by Stripe, PayPal, etc). 

Video:- https://www.awesomescreenshot.com/video/19123009?key=699ded3c7deaf41c4c6a4aec0ec552f7.
