### ISSUE TITLE
Fees are not getting recalculated on the backend when the payment gateway is changed after placing the order.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#31]
The client is having an issue where the fees are not getting recalculated on the backend when the payment gateway is changed after placing an order.

Steps to replicate:
1) Place the normal order
2) Go to Woocommerce > Orders > Edit then edit the billing details there change the payment gateway. Suppose bu default is COD, then change it to Direct Bank Transfer.
3) Click on the Recalculate button.  

After clicking on that the amount is not getting changed, the Direct Bank Transfer fee is not getting added to the total amount.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/16701

**Comment by kenil802** [comment]
Another client has also faced this issue

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/18515

**Comment by mital-tyche** [comment]
Still is was not change the fees after changing payment method.
Hence, I open the issue.
https://www.awesomescreenshot.com/video/18434074?key=009b3e40e07770abfe1e281f212378c1

**Comment by apeksha10** [comment]
The above issue is replicated with the latest git copy, 

See I have tried to change the payment gateway from Direct Bank Transfer to COD but the payment fees do not get updated after clicking on 'Recalculation' button 

https://app.screencast.com/jAmoHybx5hM85

Hence Re-open this issue
