### ISSUE TITLE
Tax is calculated incorrect.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#32]
The client wants,

Suppose, we have 2 types of VAT: 9% and 21%. Our products are subject to a 9% rate. I have choosen this low rate of 9% rate when setting up the fee in your plugin, but it still calculates 21%.

https://wordpress.org/support/topic/incorrect-tax-is-used-for-fee-tax-calculated-on-top-of-fee/

**Comment by gaminikhil** [comment]
Tax is calculated correctly. Suppose we have three types of taxes: 10%, 20%, and 30%. Our products are subject to a set 10% and 20% tax, respectively. I set a 30% tax in the payment gateway, and it is showing the correct tax calculation on the cart.

Please check the attached screenshot - https://prnt.sc/0TfHKY1Lv_an
