### ISSUE TITLE
We can add a horizontal line separator on our plugin's payment gateways page.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#33]
There are many settings in the payment gateway settings tab i.e Direct Bank Transfer, Cash on Delivery, etc. So we can add a horizontal line separator on that page to separate Fee, Additional Fees, General options section, etc.

Screenshot: https://prnt.sc/tfs7ja

**Comment by kartikparmar** [comment]
Invalid issue hence closing it
