### ISSUE TITLE
Compatibility with Mollie payment gateway.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#40]
**Describe the bug**
The issue is our plugin does not work with the Mollie payment gateway. The fees are not getting changed when we select another payment gateway after the order has been canceled.

**To Reproduce**
1) Setup the Mollie payment gateway with a sandbox account.
2) Disable the default Direct Bank Transfer payment gateway as it conflicts with the Mollie payment gateway.
3) Place an order with the Mollie Bancontact payment gateway and on the Bancontact payment page, cancel and return to the Woocommerce shop.
4) It will show this page: https://prnt.sc/uyxgsm. 
5) In this try placing an order with another payment gateway, the fees will not be calculated for that other payment gateway.

**Expected behavior**
When changing another payment gateway on the checkout page, the fees should apply for that payment gateway.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/21389

**Comment by Chetna1510** [comment]
I'm reporting here so that both issues can be fixed together.

One client has reported the issue that - Payment gateway fees not transferred to payment provider Mollie

see the video here -  https://www.veed.io/view/83558a9e-ebbc-4786-8abf-f00230e9602f?panel=share

**Comment by mital-tyche** [comment]
Mollie payment gateway plugin always throw error on my site when I activate it.
@Chetna1510 check on this one & asked me to need to do changes on Mollie plugin not in our plugin.
Hence, I will discuss about this one with @Chetna1510 & work on this one.
