### ISSUE TITLE
Fee is getting calculated incorrectly when we work with the WooCommerce Subscription plugin.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#54]
**Describe the bug**
The issue is that the fee is getting calculated incorrectly for the recurring subscription. It the showing the same fee as for the first product.

**To Reproduce**
1. Install the WooCommerce Subscription plugin 
[woocommerce-subscriptions.zip](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/files/6008741/woocommerce-subscriptions.zip)
2. Setup the Subscription as shown in the screenshot: https://prnt.sc/100mwwn, https://prnt.sc/100mxiz, https://prnt.sc/100myen, https://prnt.sc/100mz0z
3. Edit the product and select the Simple subscription and set the price to 109: https://prnt.sc/100n165 
4. Setup any payment gateway fee to 3.9 percent.
5. Add that product to the cart.
6. On the cart or on the checkout page, you will see that the fee is showing the same for both the totals.

**Expected behavior**
The fee should be calculated based on the subtotal which is there for the recurring subscription. It should not be the same fee. 

**Screenshots**
1) https://prnt.sc/100n5mk
2) https://prnt.sc/100n6rp

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/25237

**Comment by mital-tyche** [comment]
Not found any filter in woocommerce subscription plugin..
And based on code i am not sure that we are able to pass different fees for recurring...
Because for normal & recurring cart they fetched same fees. so not able to pass different fees for recurring one...
