### ISSUE TITLE
When we access the link from Invoice to pay the payment, stripe card details fields are hidden.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#69]
**Describe the bug**
I am using the Woocommerce Stripe Plugin and have Stripe and PayPal as payment options. I generated an order through the woocommerce admin page and sent the Invoice to the customer using standard woocommerce features. However, the invoice cannot be paid by the guest because the Stripe card fields are hidden while this plugin is enabled, I noticed the card entry field disappears at the tail end of page loading. This plugin is also adding instead of replacing its fees on the invoice when switching between payment options.

**To Reproduce**
1. Install 'WooCommerce Stripe Gateway' plugin- https://wordpress.org/plugins/woocommerce-gateway-stripe/
2. Enable the option in 'Payment Gateway based fees/discount' and add the fee value - https://prnt.sc/13o3orp
3. Create order from WooCommerce Order Page with Pending Payment Status
4. Send an invoice through WooCommerce Standard Option - https://prnt.sc/13o3rjy
5. Access the link from email and you won't be able to enter card details. 
6. See the error in this video - https://drive.google.com/file/d/18yzAI2DhvOFf3OpyxwSbfxONxpvYeEmi/view

**Expected behavior**
The fee should get applied at once and Card details should work when our plugin is activated.

**Additional context**
https://wordpress.org/support/topic/conflicts-with-stripe-payment-gateway-and-duplicating-fees/
The card details fields are working fine on the checkout page while placing an order from frontend.

**Comment by Chetna1510** [comment]
The client has created the ticket here - https://tychesoftwares.freshdesk.com/a/tickets/29706

**Comment by Shasvat7** [comment]
The other client had also reported this issue: https://tychesoftwares.freshdesk.com/a/tickets/29568

**Comment by Chetna1510** [comment]
One more client has reported this: https://tychesoftwares.freshdesk.com/a/tickets/29936
