### ISSUE TITLE
Product level payment gateway fees are not added to the checkout page. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/checkout-fees-for-woocommerce#71]
**Describe the bug**
Product level fees are not added to the checkout page. 

**To Reproduce**
1. Product level I have added Direct Bank Transfer fees. https://www.screencast.com/t/ibMigopbT
2. Add that product 
3. Go to the checkout page, select Direct Bank Transfer payment gateway
4. No fees are getting added in the your table. https://www.screencast.com/t/eHTY8YwDxpDb 

**Expected behavior**
Product level payment gateway fees should be added to the checkout page.

**Comment by Shasvat7** [comment]
With the latest git copy, i am unable to replicate this issue, hence closing this issue.
Screenshot: https://prnt.sc/1t6sgns
https://prnt.sc/1t6sigu
