### ISSUE TITLE
Fee is not getting calculated when order is created in the backend-manually

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#76]
**Describe the bug**
When an order is created in the backend-manually, the fee is not getting calculated.

**To Reproduce**
1. Create the order by clicking on Add Order button and keep the payment status to "Pending Payment". Screenshot: 
With Product: https://prnt.sc/1rpcrli
With Fees: https://prnt.sc/1rpcuyu

3. When you click on Customer Payment Page link it will be redirected to an Order Pay page and there the payment gateway fee is not calculated. 

With Product: https://prnt.sc/1rpda7c
With Fee: https://prnt.sc/1rpd3qp

**Isolating the problem (mark completed items with an [x]):**
- [X] This bug happens with only Payment Gateway Based Fees and Discounts for WooCommerce Pro plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront]
- [X] I can reproduce this bug consistently using the steps above

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/32686

**Comment by Shasvat7** [comment]
Added one filter for not calculating PG fees on the Woo fees when the subtotal is 0 while creating the order manually from the backend.
Check this wiki page for it: https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/wiki/Hooks-and-Filters-for-compatibility-and-minor-changes#this-will-not-calculate-the-pg-fees-on-woo-fees-when-the-subtotal-is-0-on-creating-the-order-manually
