### ISSUE TITLE
Fees & Discount are not getting applied for the individual product.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#95]
**Describe the bug**
Fees & discounts are not getting applied for the individual product. I'm using PHP 8.0.

**To Reproduce**
1. Set Discount for payment gateway on product page - https://prnt.sc/7_Bq05lMnPpm
2. No fees or discount added globally.
3. I don't see the fees on the checkout page - https://prnt.sc/fo2sGMAcpKN3

**Expected behavior**

**Screenshots**
The discount or fees should be applied per product.

**Comment by nidhinikulpatel** [comment]
I can't replicate issue with latest git copy  see the screenshots:
1.Plugin settings : https://prnt.sc/VhIxEEelFSeQ
2.edit product page settings : https://prnt.sc/u4pM3iqRd7gU
3.see the result on checkout page :https://prnt.sc/pLqQT9yZJ7JL

hence closing it.

**Comment by mital-tyche** [comment]
Still it's not applied for individual product page.
Hence, I reopen it.
