### ISSUE TITLE
Discount is getting multiplied when we try to repay the order.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#97]
**Describe the bug**
A scenerio : For money order we set %3 discount. If customer add products on cart but didn’t make payment. If he want to make payment later he can go his account > my orders and make payment. At payment page if he chose money order he can get discount %3, and select credit card discount get stuck, and one more select money order and one more %3 discount, and again and again.

**To Reproduce**
1. Create an order either from backend or frontend.
2. Then go to My Account > Orders page or use the Order page link to complete the order. 
3. You will see the issue when you refresh the page and when you switch the Payment Gateway option.

**Screenshots**
https://watch.screencastify.com/v/JXVCVeQ5TOxfRNGDsclZ

**Additional context**
https://wordpress.org/support/topic/multiple-adding-fees/

**Comment by nidhinikulpatel** [comment]
I am not able to replicate this  issue in my local see video here : https://www.awesomescreenshot.com/video/9004206?key=146d96b8499e132bae8e5fdf72b05299
hence I closing it.

**Comment by Chetna1510** [comment]
I was able to replicate this on my local server and another client has also reported this so I'm reopening this. Please check once again.
 
 https://tychesoftwares.freshdesk.com/a/tickets/41671

**Comment by Chetna1510** [comment]
One more client has reported this - https://tychesoftwares.freshdesk.com/a/tickets/41371
